import { OWNER } from '@/lib/constants';
import './globals.css';
import type { Metadata } from 'next';
import React from 'react';
import ModalProvider from '@/providers/modal-provider';
import Navbar from '@/components/navigation/navbar';

export const metadata: Metadata = {
  title: `${OWNER} | Home`,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='container mx-auto'>

        <ModalProvider />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
